### ISSUE TITLE
Multiple locations

### ISSUE THREAD

**Issue by teamcoltra** [ymichel/Geolocation-Plugin#28]
**Is your feature request related to a problem? Please describe.**
I write about trips, sometimes those trips are road trips through different locations. Or I might be talking about all my favorite restaurants in a city. Currently you must select only one location.

**Describe the solution you'd like**
I would like to input multiple locations in a single post.

Thanks so much

**Comment by ymichel** [comment]
Hi,
As mentioned on Wordpress, one can have a comparable result, when having multiple posts with Esche one location but showing them in a particular page. That page type can then also be filtered on one particular tag.
BR,
Yann
